export const weatherCode = {
    "0": "Unknown",
    "1000": ["Clear, Sunny", "clear"],
    "1100": ["Mostly Clear", ""],
    "1101": ["Partly Cloudy", ""],
    "1102": ["Mostly Cloudy", ""],
    "1001": ["Cloudy", ""],
    "2000": ["Fog",""],
    "2100": ["Light Fog", ""],
    "4000": ["Drizzle", ""],
    "4001": ["Rain", ""],
    "4200": ["Light Rain", ""],
    "4201": ["Heavy Rain", ""],
    "5000": ["Snow", ""],
    "5001": ["Flurries", ""],
    "5100": ["Light Snow", ""],
    "5101": ["Heavy Snow", ""],
    "6000": ["Freezing Drizzle", ""],
    "6001": ["Freezing Rain", ""],
    "6200": ["Light Freezing Rain", ""],
    "6201": ["Heavy Freezing Rain", ""],
    "7000": ["Ice Pellets", ""],
    "7101": ["Heavy Ice Pellets", ""],
    "7102": ["Light Ice Pellets", ""],
    "8000": ["Thunderstorm"]
  }

export const weatherCodeFullDay = {
    "0": "Unknown",
    "1000": "Clear, Sunny",
    "1100": "Mostly Clear",
    "1101": "Partly Cloudy",
    "1102": "Mostly Cloudy",
    "1001": "Cloudy",
    "1103": "Partly Cloudy and Mostly Clear",
    "2100": "Light Fog",
    "2101": "Mostly Clear and Light Fog",
    "2102": "Partly Cloudy and Light Fog",
    "2103": "Mostly Cloudy and Light Fog",
    "2106": "Mostly Clear and Fog",
    "2107": "Partly Cloudy and Fog",
    "2108": "Mostly Cloudy and Fog",
    "2000": "Fog",
    "4204": "Partly Cloudy and Drizzle",
    "4203": "Mostly Clear and Drizzle",
    "4205": "Mostly Cloudy and Drizzle",
    "4000": "Drizzle",
    "4200": "Light Rain",
    "4213": "Mostly Clear and Light Rain",
    "4214": "Partly Cloudy and Light Rain",
    "4215": "Mostly Cloudy and Light Rain",
    "4209": "Mostly Clear and Rain",
    "4208": "Partly Cloudy and Rain",
    "4210": "Mostly Cloudy and Rain",
    "4001": "Rain",
    "4211": "Mostly Clear and Heavy Rain",
    "4202": "Partly Cloudy and Heavy Rain",
    "4212": "Mostly Cloudy and Heavy Rain",
    "4201": "Heavy Rain",
    "5115": "Mostly Clear and Flurries",
    "5116": "Partly Cloudy and Flurries",
    "5117": "Mostly Cloudy and Flurries",
    "5001": "Flurries",
    "5100": "Light Snow",
    "5102": "Mostly Clear and Light Snow",
    "5103": "Partly Cloudy and Light Snow",
    "5104": "Mostly Cloudy and Light Snow",
    "5122": "Drizzle and Light Snow",
    "5105": "Mostly Clear and Snow",
    "5106": "Partly Cloudy and Snow",
    "5107": "Mostly Cloudy and Snow",
    "5000": "Snow",
    "5101": "Heavy Snow",
    "5119": "Mostly Clear and Heavy Snow",
    "5120": "Partly Cloudy and Heavy Snow",
    "5121": "Mostly Cloudy and Heavy Snow",
    "5110": "Drizzle and Snow",
    "5108": "Rain and Snow",
    "5114": "Snow and Freezing Rain",
    "5112": "Snow and Ice Pellets",
    "6000": "Freezing Drizzle",
    "6003": "Mostly Clear and Freezing drizzle",
    "6002": "Partly Cloudy and Freezing drizzle",
    "6004": "Mostly Cloudy and Freezing drizzle",
    "6204": "Drizzle and Freezing Drizzle",
    "6206": "Light Rain and Freezing Drizzle",
    "6205": "Mostly Clear and Light Freezing Rain",
    "6203": "Partly Cloudy and Light Freezing Rain",
    "6209": "Mostly Cloudy and Light Freezing Rain",
    "6200": "Light Freezing Rain",
    "6213": "Mostly Clear and Freezing Rain",
    "6214": "Partly Cloudy and Freezing Rain",
    "6215": "Mostly Cloudy and Freezing Rain",
    "6001": "Freezing Rain",
    "6212": "Drizzle and Freezing Rain",
    "6220": "Light Rain and Freezing Rain",
    "6222": "Rain and Freezing Rain",
    "6207": "Mostly Clear and Heavy Freezing Rain",
    "6202": "Partly Cloudy and Heavy Freezing Rain",
    "6208": "Mostly Cloudy and Heavy Freezing Rain",
    "6201": "Heavy Freezing Rain",
    "7110": "Mostly Clear and Light Ice Pellets",
    "7111": "Partly Cloudy and Light Ice Pellets",
    "7112": "Mostly Cloudy and Light Ice Pellets",
    "7102": "Light Ice Pellets",
    "7108": "Mostly Clear and Ice Pellets",
    "7107": "Partly Cloudy and Ice Pellets",
    "7109": "Mostly Cloudy and Ice Pellets",
    "7000": "Ice Pellets",
    "7105": "Drizzle and Ice Pellets",
    "7106": "Freezing Rain and Ice Pellets",
    "7115": "Light Rain and Ice Pellets",
    "7117": "Rain and Ice Pellets",
    "7103": "Freezing Rain and Heavy Ice Pellets",
    "7113": "Mostly Clear and Heavy Ice Pellets",
    "7114": "Partly Cloudy and Heavy Ice Pellets",
    "7116": "Mostly Cloudy and Heavy Ice Pellets",
    "7101": "Heavy Ice Pellets",
    "8001": "Mostly Clear and Thunderstorm",
    "8003": "Partly Cloudy and Thunderstorm",
    "8002": "Mostly Cloudy and Thunderstorm",
    "8000": "Thunderstorm"
  }

export const weatherCodeDay = {
    "0": "Unknown",
    "10000": ["Clear, Sunny", "clear"],
    "11000": ["Mostly Clear", "mostly_clear"],
    "11010": ["Partly Cloudy", "partly_cloudy"],
    "11020": ["Mostly Cloudy", "mostly_cloudy"],
    "10010": ["Cloudy", "cloudy"],
    "11030": ["Partly Cloudy and Mostly Clear","mostly_clear"],
    "21000": ["Light Fog", "fog_light"],
    "21010": ["Mostly Clear and Light Fog", "fog_light_mostly_clear"],
    "21020": ["Partly Cloudy and Light Fog", "fog_light_partly_cloudy"],
    "21030": ["Mostly Cloudy and Light Fog","fog_light_mostly_cloudy"],
    "21060": ["Mostly Clear and Fog","fog_mostly_clear"],
    "21070": ["Partly Cloudy and Fog","fog_partly_cloudy"],
    "21080": ["Mostly Cloudy and Fog","fog_mostly_cloudy"],
    "20000": ["Fog", "fog"],
    "42040": ["Partly Cloudy and Drizzle","drizzle_partly_cloudy"],
    "42030": ["Mostly Clear and Drizzle","drizzle_mostly_clear"],
    "42050": ["Mostly Cloudy and Drizzle","drizzle_mostly_cloudy"],
    "40000": ["Drizzle", "drizzle"],
    "42000": ["Light Rain", "rain_light"],
    "42130": ["Mostly Clear and Light Rain", "rain_light_mostly_clear"],
    "42140": ["Partly Cloudy and Light Rain","rain_light_partly_cloudy"],
    "42150": ["Mostly Cloudy and Light Rain","rain_light_mostly_cloudy"],
    "42090": ["Mostly Clear and Rain", "rain_mostly_clear"],
    "42080": ["Partly Cloudy and Rain", "rain_partly_cloudy"],
    "42100": ["Mostly Cloudy and Rain", "rain_mostly_cloudy"],
    "40010": ["Rain", "rain"],
    "42110": ["Mostly Clear and Heavy Rain", "rain_heavy_mostly_clear"],
    "42020": ["Partly Cloudy and Heavy Rain", "rain_heavy_partly_cloudy"],
    "42120": ["Mostly Cloudy and Heavy Rain", "rain_heavy_mostly_cloudy"],
    "42010": ["Heavy Rain", "rain_heavy"],
    "51150": ["Mostly Clear and Flurries", "flurries_mostly_clear"],
    "51160": ["Partly Cloudy and Flurries", "flurries_partly_cloudy"],
    "51170": ["Mostly Cloudy and Flurries", "flurries_mostly_cloudy"],
    "50010": ["Flurries","flurries"], 
    "51000": ["Light Snow", "snow_light"],
    "51020": ["Mostly Clear and Light Snow", "snow_light_mostly_clear"],
    "51030": ["Partly Cloudy and Light Snow","snow_light_partly_cloudy"],
    "51040": ["Mostly Cloudy and Light Snow", "snow_light_mostly_cloudy"],
    "51220": ["Drizzle and Light Snow", "wintry_mix"],
    "51050": ["Mostly Clear and Snow", "snow_mostly_clear"],
    "51060": ["Partly Cloudy and Snow", "snow_partly_cloudy"],
    "51070": ["Mostly Cloudy and Snow", "snow_mostly_cloudy"],
    "50000": ["Snow", "snow"],
    "51010": ["Heavy Snow", "snow_heavy"],
    "51190": ["Mostly Clear and Heavy Snow", "snow_heavy_mostly_clear"],
    "51200": ["Partly Cloudy and Heavy Snow", "snow_heavy_partly_cloudy"],
    "51210": ["Mostly Cloudy and Heavy Snow", "snow_heavy_mostly_cloudy"],
    "51100": ["Drizzle and Snow", "wintry_mix"],
    "51080": ["Rain and Snow", "wintry_mix"],
    "51140": ["Snow and Freezing Rain", "wintry_mix"],
    "51120": ["Snow and Ice Pellets", "wintry_mix"],
    "60000": ["Freezing Drizzle", "freezing_rain_drizzle"],
    "60030": ["Mostly Clear and Freezing drizzle", "freezing_rain_drizzle_mostly_clear"],
    "60020": ["Partly Cloudy and Freezing drizzle", "freezing_rain_drizzle_partly_cloudy"],
    "60040": ["Mostly Cloudy and Freezing drizzle", "freezing_rain_drizzle_mostly_cloudy"],
    "62040": ["Drizzle and Freezing Drizzle", "wintry_mix"],
    "62060": ["Light Rain and Freezing Drizzle", "wintry_mix"],
    "62050": ["Mostly Clear and Light Freezing Rain", "freezing_rain_light_mostly_clear"],
    "62030": ["Partly Cloudy and Light Freezing Rain", "freezing_rain_light_partly_cloudy"],
    "62090": ["Mostly Cloudy and Light Freezing Rain",  "freezing_rain_light_mostly_cloudy"],
    "62000": ["Light Freezing Rain", "freezing_rain_light"],
    "62130": ["Mostly Clear and Freezing Rain", "freezing_rain_mostly_clear"],
    "62140": ["Partly Cloudy and Freezing Rain", "freezing_rain_partly_cloudy"],
    "62150": ["Mostly Cloudy and Freezing Rain", "freezing_rain_mostly_cloudy"],
    "60010": ["Freezing Rain", "freezing_rain"],
    "62120": ["Drizzle and Freezing Rain", "wintry_mix"],
    "62200": ["Light Rain and Freezing Rain", "wintry_mix"],
    "62220": ["Rain and Freezing Rain", "wintry_mix"],
    "62070": ["Mostly Clear and Heavy Freezing Rain", "freezing_rain_mostly_clear"],
    "62020": ["Partly Cloudy and Heavy Freezing Rain",  "freezing_rain_partly_cloudy"],
    "62080": ["Mostly Cloudy and Heavy Freezing Rain",  "freezing_rain_mostly_cloudy"],
    "62010": ["Heavy Freezing Rain", "freezing_rain_heavy"],
    "71100": ["Mostly Clear and Light Ice Pellets", "ice_pellets_light_mostly_clear"],
    "71110": ["Partly Cloudy and Light Ice Pellets", "ice_pellets_light_partly_cloudy"],
    "71120": ["Mostly Cloudy and Light Ice Pellets", "ice_pellets_light_mostly_cloudy"],
    "71020": ["Light Ice Pellets", "ice_pellets_light"],
    "71080": ["Mostly Clear and Ice Pellets", "ice_pellets_mostly_clear"],
    "71070": ["Partly Cloudy and Ice Pellets", "ice_pellets_partly_cloudy"],
    "71090": ["Mostly Cloudy and Ice Pellets", "ice_pellets_mostly_cloudy"],
    "70000": ["Ice Pellets", "ice_pellets"],
    "71050": ["Drizzle and Ice Pellets", "wintry_mix"],
    "71060": ["Freezing Rain and Ice Pellets", "wintry_mix"],
    "71150": ["Light Rain and Ice Pellets", "wintry_mix"],
    "71170": ["Rain and Ice Pellets", "wintry_mix"],
    "71030": ["Freezing Rain and Heavy Ice Pellets", "wintry_mix"],
    "71130": ["Mostly Clear and Heavy Ice Pellets", "ice_pellets_heavy_mostly_clear"],
    "71140": ["Partly Cloudy and Heavy Ice Pellets", "ice_pellets_heavy_partly_cloudy"],
    "71160": ["Mostly Cloudy and Heavy Ice Pellets", "ice_pellets_heavy_mostly_cloudy"],
    "71010": ["Heavy Ice Pellets", "ice_pellets_heavy"],
    "80010": ["Mostly Clear and Thunderstorm", "tstorm_mostly_clear"],
    "80030": ["Partly Cloudy and Thunderstorm", "tstorm_partly_cloudy"],
    "80020": ["Mostly Cloudy and Thunderstorm", "tstorm_mostly_cloudy"],
    "80000": ["Thunderstorm", "tstorm"],
  }

export const weatherCodeNight = {
    "0": "Unknown",
    "10001": ["Clear", "clear"],
    "11001": ["Mostly Clear", "mostly_clear"],
    "11011": ["Partly Cloudy", "partly_cloudy"],
    "11021": ["Mostly Cloudy", "mostly_cloudy"],
    "10011": ["Cloudy", "cloudy"],
    "11031": ["Partly Cloudy and Mostly Clear", "mostly_clear"],
    "21001": ["Light Fog", "fog_light"],
    "21011": ["Mostly Clear and Light Fog", "fog_light_mostly_clear"],
    "21021": ["Partly Cloudy and Light Fog", "fog_light_partly_cloudy"],
    "21031": ["Mostly Cloudy and Light Fog", "fog_light_mostly_cloudy"],
    "21061": ["Mostly Clear and Fog", "fog_mostly_clear"],
    "21071": ["Partly Cloudy and Fog", "fog_partly_cloudy"],
    "21081": ["Mostly Cloudy and Fog", "fog_mostly_cloudy"],
    "20001": ["Fog", "fog"],
    "42041": ["Partly Cloudy and Drizzle", "drizzle_partly_cloudy"],
    "42031": ["Mostly Clear and Drizzle", "drizzle_mostly_clear"],
    "42051": ["Mostly Cloudy and Drizzle", "drizzle_mostly_cloudy"],
    "40001": ["Drizzle", "drizzle"],
    "42001": ["Light Rain", "rain_light"],
    "42131": ["Mostly Clear and Light Rain", "rain_light_mostly_clear"],
    "42141": ["Partly Cloudy and Light Rain", "rain_light_partly_cloudy"],
    "42151": ["Mostly Cloudy and Light Rain", "rain_light_mostly_cloudy"],
    "42091": ["Mostly Clear and Rain", "rain_mostly_clear"],
    "42081": ["Partly Cloudy and Rain", "rain_partly_cloudy"],
    "42101": ["Mostly Cloudy and Rain", "rain_mostly_cloudy"],
    "40011": ["Rain", "rain"],
    "42111": ["Mostly Clear and Heavy Rain", "rain_heavy_mostly_clear"],
    "42021": ["Partly Cloudy and Heavy Rain", "rain_heavy_partly_cloudy"],
    "42121": ["Mostly Cloudy and Heavy Rain", "rain_heavy_mostly_cloudy"],
    "42011": ["Heavy Rain", "rain_heavy"],
    "51151": ["Mostly Clear and Flurries", "flurries_mostly_clear"],
    "51161": ["Partly Cloudy and Flurries", "flurries_partly_cloudy"],
    "51171": ["Mostly Cloudy and Flurries", "flurries_mostly_cloudy"],
    "50011": ["Flurries", "flurries"],
    "51001": ["Light Snow", "snow_light"],
    "51021": ["Mostly Clear and Light Snow", "snow_light_mostly_clear"],
    "51031": ["Partly Cloudy and Light Snow", "snow_light_partly_cloudy"],
    "51041": ["Mostly Cloudy and Light Snow", "snow_light_mostly_cloudy"],
    "51221": ["Drizzle and Light Snow", "wintry_mix"],
    "51051": ["Mostly Clear and Snow", "snow_mostly_clear"],
    "51061": ["Partly Cloudy and Snow", "snow_partly_cloudy"],
    "51071": ["Mostly Cloudy and Snow", "snow_mostly_cloudy"],
    "50001": ["Snow", "snow"],
    "51011": ["Heavy Snow", "snow_heavy"],
    "51191": ["Mostly Clear and Heavy Snow", "snow_heavy_mostly_clear"],
    "51201": ["Partly Cloudy and Heavy Snow", "snow_heavy_partly_cloudy"],
    "51211": ["Mostly Cloudy and Heavy Snow", "snow_heavy_mostly_cloudy"],
    "51101": ["Drizzle and Snow", "wintry_mix"],
    "51081": ["Rain and Snow", "wintry_mix"],
    "51141": ["Snow and Freezing Rain", "wintry_mix"],
    "51121": ["Snow and Ice Pellets", "wintry_mix"],
    "60001": ["Freezing Drizzle", "freezing_rain_drizzle"],
    "60031": ["Mostly Clear and Freezing drizzle", "freezing_rain_drizzle_mostly_clear"],
    "60021": ["Partly Cloudy and Freezing drizzle", "freezing_rain_drizzle_partly_cloudy"],
    "60041": ["Mostly Cloudy and Freezing drizzle", "freezing_rain_drizzle_mostly_cloudy"],
    "62041": ["Drizzle and Freezing Drizzle", "wintry_mix"],
    "62061": ["Light Rain and Freezing Drizzle", "wintry_mix"],
    "62051": ["Mostly Clear and Light Freezing Rain", "freezing_rain_light_mostly_clear"],
    "62031": ["Partly cloudy and Light Freezing Rain", "freezing_rain_light_partly_cloudy"],
    "62091": ["Mostly Cloudy and Light Freezing Rain", "freezing_rain_light_mostly_cloudy"],
    "62001": ["Light Freezing Rain", "freezing_rain_light"],
    "62131": ["Mostly Clear and Freezing Rain", "freezing_rain_mostly_clear"],
    "62141": ["Partly Cloudy and Freezing Rain", "freezing_rain_partly_cloudy"],
    "62151": ["Mostly Cloudy and Freezing Rain", "freezing_rain_mostly_cloudy"],
    "60011": ["Freezing Rain", "freezing_rain"],
    "62121": ["Drizzle and Freezing Rain", "wintry_mix"],
    "62201": ["Light Rain and Freezing Rain", "wintry_mix"],
    "62221": ["Rain and Freezing Rain", "wintry_mix"],
    "62071": ["Mostly Clear and Heavy Freezing Rain", "freezing_rain_heavy_mostly_clear"],
    "62021": ["Partly Cloudy and Heavy Freezing Rain", "freezing_rain_heavy_partly_cloudy"],
    "62081": ["Mostly Cloudy and Heavy Freezing Rain", "freezing_rain_heavy_mostly_cloudy"],
    "62011": ["Heavy Freezing Rain", "freezing_rain_heavy"],
    "71101": ["Mostly Clear and Light Ice Pellets", "ice_pellets_light_mostly_clear"],
    "71111": ["Partly Cloudy and Light Ice Pellets", "ice_pellets_light_partly_cloudy"],
    "71121": ["Mostly Cloudy and Light Ice Pellets", "ice_pellets_light_mostly_cloudy"],
    "71021": ["Light Ice Pellets", "ice_pellets_light"],
    "71081": ["Mostly Clear and Ice Pellets", "ice_pellets_mostly_clear"],
    "71071": ["Partly Cloudy and Ice Pellets", "ice_pellets_light_partly_cloudy"],
    "71091": ["Mostly Cloudy and Ice Pellets", "ice_pellets_light_mostly_cloudy"],
    "70001": ["Ice Pellets", "ice_pellets"],
    "71051": ["Drizzle and Ice Pellets", "wintry_mix"],
    "71061": ["Freezing Rain and Ice Pellets", "wintry_mix"],
    "71151": ["Light Rain and Ice Pellets", "wintry_mix"],
    "71171": ["Rain and Ice Pellets", "wintry_mix"],
    "71031": ["Freezing Rain and Heavy Ice Pellets", "wintry_mix"],
    "71131": ["Mostly Clear and Heavy Ice Pellets", "ice_pellets_heavy_mostly_clear"],
    "71141": ["Partly Cloudy and Heavy Ice Pellets", "ice_pellets_heavy_partly_cloudy"],
    "71161": ["Mostly Cloudy and Heavy Ice Pellets", "ice_pellets_heavy_mostly_cloudy"],
    "71011": ["Heavy Ice Pellets", "ice_pellets_heavy"],
    "80011": ["Mostly Clear and Thunderstorm", "tstorm_mostly_clear"],
    "80031": ["Partly Cloudy and Thunderstorm", "storm_partly_cloudy"],
    "80021": ["Mostly Cloudy and Thunderstorm", "storm_mostly_cloudy"],
    "80001": ["Thunderstorm", "tstorm"]
  }